# Generated by Django 3.2.9 on 2021-11-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('College_ID', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=122)),
                ('status', models.CharField(choices=[('Red', 'Not yet Vaccinated'), ('Yellow', 'Partially Vaccinated'), ('Green', 'Fully Vaccinated')], max_length=6)),
                ('proof', models.CharField(choices=[('Aadhar', 'Aadhaar Card'), ('PAN', 'PAN Card')], max_length=6)),
                ('verification_ID', models.CharField(max_length=50)),
            ],
        ),
    ]
