# Generated by Django 3.2.9 on 2021-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='edit',
            name='College_ID',
            field=models.CharField(max_length=122),
        ),
    ]
