# Generated by Django 3.2.9 on 2021-11-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211126_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='College_ID',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
