# Generated by Django 3.2.9 on 2021-11-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_edit_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='College_ID',
            field=models.CharField(default='BYYYXXXZZ', max_length=122),
        ),
    ]
