# Generated by Django 3.2.9 on 2021-11-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_edit_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='email',
            field=models.CharField(default='Not Provided', max_length=122),
        ),
        migrations.AlterField(
            model_name='edit',
            name='name',
            field=models.CharField(default='Not Provided', max_length=122),
        ),
        migrations.AlterField(
            model_name='edit',
            name='proof',
            field=models.CharField(choices=[('Aadhar', 'Aadhaar Card'), ('PAN', 'PAN Card')], default='Not Provided', max_length=6),
        ),
        migrations.AlterField(
            model_name='edit',
            name='status',
            field=models.CharField(choices=[('Red', 'Not yet Vaccinated'), ('Yellow', 'Partially Vaccinated'), ('Green', 'Fully Vaccinated')], default='Not Provided', max_length=6),
        ),
        migrations.AlterField(
            model_name='edit',
            name='verification_ID',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
    ]
