# Generated by Django 3.2.9 on 2021-11-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211126_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='College_ID',
            field=models.CharField(default='Not Provided', max_length=122),
        ),
    ]
