# Generated by Django 3.2.9 on 2021-11-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211126_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='verification_ID',
            field=models.PositiveIntegerField(blank=True, default='Not Provided', max_length=50, null=True),
        ),
    ]
