# Generated by Django 3.2.9 on 2021-11-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211126_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='College_ID',
            new_name='collegeid',
        ),
    ]
