# Generated by Django 3.2.9 on 2021-11-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_college_id_edit_collegeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='verification_ID',
            new_name='verificationid',
        ),
    ]
