# Generated by Django 3.2.9 on 2021-11-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211126_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='collegeid',
            field=models.CharField(blank=True, default='Not Provided', max_length=122, null=True, unique='True'),
        ),
    ]
