# Generated by Django 3.2.9 on 2021-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211128_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='email',
            field=models.CharField(default='Not Provided', max_length=122),
        ),
        migrations.AlterField(
            model_name='edit',
            name='name',
            field=models.CharField(default='Not Provided', max_length=122),
        ),
    ]
