# Generated by Django 3.2.9 on 2021-11-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211128_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edit',
            new_name='Upload',
        ),
    ]
