# Generated by Django 3.2.9 on 2021-11-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_edit_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(default='settings.MEDIA_ROOT/pdfs/default.pdf', upload_to='pdfs'),
        ),
    ]
