# Generated by Django 3.2.9 on 2021-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_upload_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload_file',
            new_name='verificationpdf',
        ),
        migrations.AlterField(
            model_name='upload',
            name='proof',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('PAN Card', 'PAN Card'), ('Mobile Number', 'Mobile Number')], default='Aadhar Card', max_length=122),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('Not Yet Vaccinated', 'Not Yet Vaccinated'), ('Partially Vaccinated', 'Partially Vaccinated'), ('Fully Vaccinated', 'Fully Vaccinated')], default='Not Yet Vaccinated', max_length=122),
        ),
    ]
