# Generated by Django 3.2.9 on 2021-11-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211128_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='collegeid',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='upload',
            name='verificationid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
